CREATE TABLE [dbo].[KISILER1](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[AD] [varchar](30) NULL,
	[SOYISIM] [varchar](30) NULL,
	[DOGUMTARIHI] [date] NULL,
	[YAS] [int] NULL,
	[YASGRUBU] [varchar](30) NULL,
	[EPOSTA] [varchar](30) NULL,
	[STATENAME] [varchar](30) NULL,
	[CITY] [varchar](30) NULL,
	[STREET] [varchar](30) NULL,
	[ZIP] [varchar](30) NULL
) ON [PRIMARY]

DECLARE @I AS INT=0
WHILE @I < 900000
BEGIN
DECLARE @AD AS VARCHAR (50)
DECLARE @SOYAD VARCHAR (50)
DECLARE @DOGUMTARIHI DATE
DECLARE @YAS AS INT
DECLARE @YASGRUBU AS VARCHAR (30)
DECLARE @EPOSTA AS VARCHAR (30)
DECLARE @EPOSTAT AS VARCHAR (30)
DECLARE @STATE AS VARCHAR(30)
DECLARE @CITY AS VARCHAR (30)
DECLARE @STREET AS VARCHAR (50)
DECLARE @ZIP AS INT	
SELECT @AD=AD FROM ISIMLER WHERE ID =ROUND(RAND() * 1676,0)
SELECT @SOYAD=SOYISIM FROM SOYISIMLER WHERE ID =ROUND(RAND() * 1676,0)
SELECT @EPOSTA=EMAILDOMAIN FROM EMAIL WHERE ID =ROUND(RAND() * 9,0)
SELECT @STREET=STREET FROM STREET WHERE ID =ROUND(RAND() * 1000,0)
SELECT @CITY=CITY, @STATE=STATENAME FROM STATE WHERE ID =ROUND(RAND() * 50,0)
SET @ZIP= ROUND(RAND()*99999,0);
SET @DOGUMTARIHI= DATEADD (DAY, ROUND(RAND()*18250,0),'1950-01-01')
SET @YAS =DATEDIFF(YEAR, @DOGUMTARIHI,GETDATE())
SET @EPOSTAT = @AD+ @SOYAD+'@'+@EPOSTA
IF @YAS BETWEEN 10 AND 20
SET @YASGRUBU ='KUCUK'
	IF @YAS BETWEEN 21 AND 40
SET @YASGRUBU ='ORTA YAS'
	IF @YAS BETWEEN 41 AND 60
SET @YASGRUBU ='BUYUK'
	IF @YAS >60
SET @YASGRUBU ='YAÞLI'
INSERT INTO KISILER1 (AD, SOYISIM, DOGUMTARIHI, YAS, YASGRUBU,EPOSTA, STATENAME, CITY, STREET, ZIP) VALUES (@AD, @SOYAD, @DOGUMTARIHI, @YAS, @YASGRUBU, @EPOSTAT, @STATE, @CITY, @STREET,@ZIP)
SET @I=@I+1
END


-- index i sýfýrlar ve tablodaki kayýtlarý siler.

truncate table[dbo].[KISILER1]

-- tablo içinde çok hýzlý bir þekilde ne kadar kayýt olduðunu gösterir

sp_spaceused [dbo].[KISILER1]

-- indexleme yapýyoruz

select count (*) from KISILER1

SET STATISTICS TIME ON
SET STATISTICS IO ON 

select top 100 * from KISILER1

select top 100 * from KISILER1
where id = 123112



select top 100 * from KISILER1
where AD = 'Susan' AND SOYISIM ='Horton' AND YAS=67

SET STATISTICS TIME ON
SET STATISTICS IO ON 

